---
- name: Setup VM with Podman
  hosts: webserver
  become: yes

  tasks:
    - name: Install packages for Podman
      apt:
        name:
          - podman
          - apache2-utils
          - openssl
        state: present
        update_cache: yes

    - name: Enable and start Podman socket
      systemd:
        name: podman.socket
        state: started
        enabled: yes
